#! /usr/bin/bash
set -e
mv a-dried-sour-kefir-gsk-q-rit-3-/data/versionXML.flextext a-dried-sour-kefir-gsk-q-rit-3-.xml
mv a-fairy-tale-msk-inda/data/versionXML.flextext a-fairy-tale-msk-inda.xml
mv a-foolish-boy-msk-biaql-kas-3-/data/versionXML.flextext a-foolish-boy-msk-biaql-kas-3-.xml
mv a-foolish-man-msk-biaql-aj-3-/data/versionXML.flextext a-foolish-man-msk-biaql-aj-3-.xml
mv a-golden-hen-msk-m-r-i-zarin-3-/data/versionXML.flextext a-golden-hen-msk-m-r-i-zarin-3-.xml
mv a-golden-saddle-ela-tiloi-p-dn-3-/data/versionXML.flextext a-golden-saddle-ela-tiloi-p-dn-3-.xml
mv a-golden-saddle-msk-tilloi-p-dn-2-/data/versionXML.flextext a-golden-saddle-msk-tilloi-p-dn-2-.xml
mv a-loser-msk-gat-k-3-/data/versionXML.flextext a-loser-msk-gat-k-3-.xml
mv a-rich-man-pkh-ji-boj/data/versionXML.flextext a-rich-man-pkh-ji-boj.xml
mv a-smart-bald-boy-msk-kali-zirak/data/versionXML.flextext a-smart-bald-boy-msk-kali-zirak.xml
mv about-the-wakhi-language-ela-dar-borai-c-ikwor-zik-3-/data/versionXML.flextext about-the-wakhi-language-ela-dar-borai-c-ikwor-zik-3-.xml
mv ambar-pamir-song-ela-ambari-pomir-3-/data/versionXML.flextext ambar-pamir-song-ela-ambari-pomir-3-.xml
mv children-s-games-gsk-jeux-d-enfants-2-/data/versionXML.flextext children-s-games-gsk-jeux-d-enfants-2-.xml
mv columbia-fieldmethods-elicitation-fall-2011-3-/data/versionXML.flextext columbia-fieldmethods-elicitation-fall-2011-3-.xml
mv columbia-fieldmethods-elicitation-spring-2012-3-/data/versionXML.flextext columbia-fieldmethods-elicitation-spring-2012-3-.xml
mv complement-clauses-3-/data/versionXML.flextext complement-clauses-3-.xml
mv davlatmo-bairambekova-ela-davlatmo-bairambekova-2-/data/versionXML.flextext davlatmo-bairambekova-ela-davlatmo-bairambekova-2-.xml
mv dictionary-examples-3-/data/versionXML.flextext dictionary-examples-3-.xml
mv earning-an-ethical-living-ela-minati-alol/data/versionXML.flextext earning-an-ethical-living-ela-minati-alol.xml
mv ela-a-miracle-for-bobo-sufi-s-family-3-/data/versionXML.flextext ela-a-miracle-for-bobo-sufi-s-family-3-.xml
mv ela-a-rich-man-and-his-beautiful-daughter-3-/data/versionXML.flextext ela-a-rich-man-and-his-beautiful-daughter-3-.xml
mv ela-bilbilik-matluba-3-/data/versionXML.flextext ela-bilbilik-matluba-3-.xml
mv ela-bobo-sufi-was-living-in-avgarch/data/versionXML.flextext ela-bobo-sufi-was-living-in-avgarch.xml
mv ela-comparing-the-wakhis-of-afghanistan-and-tajikistan-3-/data/versionXML.flextext ela-comparing-the-wakhis-of-afghanistan-and-tajikistan-3-.xml
mv ela-documenting-the-songs-of-his-people/data/versionXML.flextext ela-documenting-the-songs-of-his-people.xml
mv ela-from-herder-to-engineer/data/versionXML.flextext ela-from-herder-to-engineer.xml
mv ela-historical-sites-of-the-pamir-region/data/versionXML.flextext ela-historical-sites-of-the-pamir-region.xml
mv ela-how-it-feels-to-sing-bilbilik/data/versionXML.flextext ela-how-it-feels-to-sing-bilbilik.xml
mv ela-kingir/data/versionXML.flextext ela-kingir.xml
mv ela-lalajik-lullaby-asalbegim-/data/versionXML.flextext ela-lalajik-lullaby-asalbegim-.xml
mv ela-life-as-a-wakhi-russian/data/versionXML.flextext ela-life-as-a-wakhi-russian.xml
mv ela-maiden-s-tower/data/versionXML.flextext ela-maiden-s-tower.xml
mv ela-on-the-wakhis-in-china/data/versionXML.flextext ela-on-the-wakhis-in-china.xml
mv ela-skort-i/data/versionXML.flextext ela-skort-i.xml
mv ela-the-king-s-son-and-the-vizier-s-son/data/versionXML.flextext ela-the-king-s-son-and-the-vizier-s-son.xml
mv ela-the-meaning-of-my-lullaby/data/versionXML.flextext ela-the-meaning-of-my-lullaby.xml
mv ela-the-meaning-of-our-bilbilik-/data/versionXML.flextext ela-the-meaning-of-our-bilbilik-.xml
mv ela-the-story-of-toshkhon-and-gulqurbon/data/versionXML.flextext ela-the-story-of-toshkhon-and-gulqurbon.xml
mv ela-traditional-wakhi-clothing/data/versionXML.flextext ela-traditional-wakhi-clothing.xml
mv ela-treasuring-our-language/data/versionXML.flextext ela-treasuring-our-language.xml
mv ela-wakhi-across-europe-and-asia/data/versionXML.flextext ela-wakhi-across-europe-and-asia.xml
mv ela-wakhi-american-ela-c-ik-de-amerika/data/versionXML.flextext ela-wakhi-american-ela-c-ik-de-amerika.xml
mv ela-wakhi-proverbs-3-/data/versionXML.flextext ela-wakhi-proverbs-3-.xml
mv ela-xikwor-qesoid-wakhi-ode-/data/versionXML.flextext ela-xikwor-qesoid-wakhi-ode-.xml
mv ela-zi-q-soid-mani-the-meaning-of-my-ode-/data/versionXML.flextext ela-zi-q-soid-mani-the-meaning-of-my-ode-.xml
mv ela-zi-timtang-najdi-mod-in/data/versionXML.flextext ela-zi-timtang-najdi-mod-in.xml
mv funeral-song-ela-ruboi-am-/data/versionXML.flextext funeral-song-ela-ruboi-am-.xml
mv gsk-ajloq-3-/data/versionXML.flextext gsk-ajloq-3-.xml
mv gsk-augures-lies-a-la-cuisson-du-pain-briquet-/data/versionXML.flextext gsk-augures-lies-a-la-cuisson-du-pain-briquet-.xml
mv gsk-b-lbalik/data/versionXML.flextext gsk-b-lbalik.xml
mv gsk-devinettes-3-/data/versionXML.flextext gsk-devinettes-3-.xml
mv gsk-dictons-et-proverbes-3-/data/versionXML.flextext gsk-dictons-et-proverbes-3-.xml
mv gsk-diqoni-3-/data/versionXML.flextext gsk-diqoni-3-.xml
mv gsk-dressage-des-oiseaux-pour-la-chasse-3-/data/versionXML.flextext gsk-dressage-des-oiseaux-pour-la-chasse-3-.xml
mv gsk-fumier-animal/data/versionXML.flextext gsk-fumier-animal.xml
mv gsk-k-mpirzan-3-/data/versionXML.flextext gsk-k-mpirzan-3-.xml
mv gsk-l-oisillon-enchante-/data/versionXML.flextext gsk-l-oisillon-enchante-.xml
mv gsk-la-reine-aux-cheveux-longs-de-quarante-gazes/data/versionXML.flextext gsk-la-reine-aux-cheveux-longs-de-quarante-gazes.xml
mv gsk-le-dive-et-la-fille-du-roi/data/versionXML.flextext gsk-le-dive-et-la-fille-du-roi.xml
mv gsk-le-meunier-chauve-et-le-renard/data/versionXML.flextext gsk-le-meunier-chauve-et-le-renard.xml
mv gsk-le-preux-ziemtchi/data/versionXML.flextext gsk-le-preux-ziemtchi.xml
mv gsk-maaraka/data/versionXML.flextext gsk-maaraka.xml
mv gsk-me-decine-traditionnelle/data/versionXML.flextext gsk-me-decine-traditionnelle.xml
mv gsk-ogin-3-/data/versionXML.flextext gsk-ogin-3-.xml
mv gsk-os-de-bovins-et-de-caprins-3-/data/versionXML.flextext gsk-os-de-bovins-et-de-caprins-3-.xml
mv gsk-pand-tani-t-orjori-3-/data/versionXML.flextext gsk-pand-tani-t-orjori-3-.xml
mv gsk-pre-paration-de-la-nourriture/data/versionXML.flextext gsk-pre-paration-de-la-nourriture.xml
mv gsk-q-rbon-id-3-/data/versionXML.flextext gsk-q-rbon-id-3-.xml
mv gsk-quelques-rites-3-/data/versionXML.flextext gsk-quelques-rites-3-.xml
mv gsk-s-ira-3-/data/versionXML.flextext gsk-s-ira-3-.xml
mv gsk-s-jd-xun-c-ak-sij-skor-3-/data/versionXML.flextext gsk-s-jd-xun-c-ak-sij-skor-3-.xml
mv gsk-tawallidi-bats-a-za-t-r-bar-nic-vak-3-/data/versionXML.flextext gsk-tawallidi-bats-a-za-t-r-bar-nic-vak-3-.xml
mv gsk-tuj-2-/data/versionXML.flextext gsk-tuj-2-.xml
mv gsk-waxon-3-/data/versionXML.flextext gsk-waxon-3-.xml
mv gsk-x-doji-3-/data/versionXML.flextext gsk-x-doji-3-.xml
mv gsk-zman-c-ak-3-/data/versionXML.flextext gsk-zman-c-ak-3-.xml
mv i-am-not-going-to-plow-anymore-msk-wuz-b-t-kirak-n-r-ts-m-7/data/versionXML.flextext i-am-not-going-to-plow-anymore-msk-wuz-b-t-kirak-n-r-ts-m-7.xml
mv i-am-unaware-msk-wuz-m-bixbar/data/versionXML.flextext i-am-unaware-msk-wuz-m-bixbar.xml
mv i-came-to-the-entrance-msk-wuz-m-w-zg-d-m-bizowis-4/data/versionXML.flextext i-came-to-the-entrance-msk-wuz-m-w-zg-d-m-bizowis-4.xml
mv i-sacrifice-myself-for-my-darling-5-msk-wuz-c-i-dir-r-jir-m-5/data/versionXML.flextext i-sacrifice-myself-for-my-darling-5-msk-wuz-c-i-dir-r-jir-m-5.xml
mv i-sacrifice-myself-for-my-flower-1-msk-wuz-c-i-gil-r-jir-m-1/data/versionXML.flextext i-sacrifice-myself-for-my-flower-1-msk-wuz-c-i-gil-r-jir-m-1.xml
mv i-sacrifice-myself-for-my-flower-2-msk-wuz-c-i-gil-r-jir-m-2/data/versionXML.flextext i-sacrifice-myself-for-my-flower-2-msk-wuz-c-i-gil-r-jir-m-2.xml
mv i-sacrifice-myself-for-my-flower-3-msk-wuz-c-i-gil-r-jir-m-3/data/versionXML.flextext i-sacrifice-myself-for-my-flower-3-msk-wuz-c-i-gil-r-jir-m-3.xml
mv i-sacrifice-myself-for-my-flower-6-msk-wuz-c-i-gil-r-jir-m-6/data/versionXML.flextext i-sacrifice-myself-for-my-flower-6-msk-wuz-c-i-gil-r-jir-m-6.xml
mv i-sing-to-you-like-a-nightingale-ela-bilbilik-bilbil-tar-nolime-3-/data/versionXML.flextext i-sing-to-you-like-a-nightingale-ela-bilbilik-bilbil-tar-nolime-3-.xml
mv kingir-msk-kingir/data/versionXML.flextext kingir-msk-kingir.xml
mv let-s-go-to-the-orchard-s-shade-place-msk-lapar-tsa-tsa-ta-bo-soja-3-/data/versionXML.flextext let-s-go-to-the-orchard-s-shade-place-msk-lapar-tsa-tsa-ta-bo-soja-3-.xml
mv lullaby-pakistan-ela-lalajik-pakistan-/data/versionXML.flextext lullaby-pakistan-ela-lalajik-pakistan-.xml
mv lullaby-tajikistan-ela-lalajik-tajikistan-/data/versionXML.flextext lullaby-tajikistan-ela-lalajik-tajikistan-.xml
mv maj-zman-gsk-maj-zman-3-/data/versionXML.flextext maj-zman-gsk-maj-zman-3-.xml
mv msk-a-waxt-ki-mawsimi-baor-3-/data/versionXML.flextext msk-a-waxt-ki-mawsimi-baor-3-.xml
mv msk-arxil-q-sai-/data/versionXML.flextext msk-arxil-q-sai-.xml
mv msk-baor-w-zd-ar-gilistoni-d-woni-3-/data/versionXML.flextext msk-baor-w-zd-ar-gilistoni-d-woni-3-.xml
mv msk-bilbilik/data/versionXML.flextext msk-bilbilik.xml
mv msk-bilbilik-afghanistan-3-/data/versionXML.flextext msk-bilbilik-afghanistan-3-.xml
mv msk-c-ik-p-rt-od-3-/data/versionXML.flextext msk-c-ik-p-rt-od-3-.xml
mv msk-didor-mar-nasib-mawlo-3-/data/versionXML.flextext msk-didor-mar-nasib-mawlo-3-.xml
mv msk-e-c-ik-p-rt-od-tu-raqs-tsar-3-/data/versionXML.flextext msk-e-c-ik-p-rt-od-tu-raqs-tsar-3-.xml
mv msk-f-qir-m-wuz-3-/data/versionXML.flextext msk-f-qir-m-wuz-3-.xml
mv msk-gil-tar-ts-ford-3-/data/versionXML.flextext msk-gil-tar-ts-ford-3-.xml
mv msk-i-q-t-d-zi-pziv-tu-kart/data/versionXML.flextext msk-i-q-t-d-zi-pziv-tu-kart.xml
mv msk-lalajik-2-/data/versionXML.flextext msk-lalajik-2-.xml
mv msk-lapar/data/versionXML.flextext msk-lapar.xml
mv msk-m-tali-2-/data/versionXML.flextext msk-m-tali-2-.xml
mv msk-nasijat-3-/data/versionXML.flextext msk-nasijat-3-.xml
mv msk-ogin-baor-m-borak-2-/data/versionXML.flextext msk-ogin-baor-m-borak-2-.xml
mv msk-ogin-m-borak-wuz-c-an-m-2-/data/versionXML.flextext msk-ogin-m-borak-wuz-c-an-m-2-.xml
mv msk-ogin-sav-r-m-borak-2-/data/versionXML.flextext msk-ogin-sav-r-m-borak-2-.xml
mv msk-p-rwo-m-tsar/data/versionXML.flextext msk-p-rwo-m-tsar.xml
mv msk-r-ts-m/data/versionXML.flextext msk-r-ts-m.xml
mv msk-ruboi-1/data/versionXML.flextext msk-ruboi-1.xml
mv msk-ruboi-2/data/versionXML.flextext msk-ruboi-2.xml
mv msk-ruboi-4/data/versionXML.flextext msk-ruboi-4.xml
mv msk-ruboi-5-3-/data/versionXML.flextext msk-ruboi-5-3-.xml
mv msk-ruboi-6/data/versionXML.flextext msk-ruboi-6.xml
mv msk-t-istoni-translate-/data/versionXML.flextext msk-t-istoni-translate-.xml
mv msk-waxoni-n-r-ms-m/data/versionXML.flextext msk-waxoni-n-r-ms-m.xml
mv msk-x-st-zi-jo-i-2-/data/versionXML.flextext msk-x-st-zi-jo-i-2-.xml
mv mullahs-s-son-msk-domlo-p-tr-2-/data/versionXML.flextext mullahs-s-son-msk-domlo-p-tr-2-.xml
mv my-life-ela-zi-zindagi/data/versionXML.flextext my-life-ela-zi-zindagi.xml
mv oh-mother-msk-wuz-ej-nan/data/versionXML.flextext oh-mother-msk-wuz-ej-nan.xml
mv old-woman-village-ela-kimpir-dyor/data/versionXML.flextext old-woman-village-ela-kimpir-dyor.xml
mv pkh-boz-rgon/data/versionXML.flextext pkh-boz-rgon.xml
mv pkh-hib-aqlim-r-potso-tu-2-/data/versionXML.flextext pkh-hib-aqlim-r-potso-tu-2-.xml
mv pkh-i-pot-o-2-/data/versionXML.flextext pkh-i-pot-o-2-.xml
mv pkh-ir-k-b-mi-ir-/data/versionXML.flextext pkh-ir-k-b-mi-ir-.xml
mv pkh-ji-n-xt-ir-tu/data/versionXML.flextext pkh-ji-n-xt-ir-tu.xml
mv pkh-satk-kb-iw-t-buj/data/versionXML.flextext pkh-satk-kb-iw-t-buj.xml
mv pkh-sayings/data/versionXML.flextext pkh-sayings.xml
mv pkh-tsibir-vrit/data/versionXML.flextext pkh-tsibir-vrit.xml
mv rahila-ela-life-as-a-wakhi-american/data/versionXML.flextext rahila-ela-life-as-a-wakhi-american.xml
mv reinhardt-text-2/data/versionXML.flextext reinhardt-text-2.xml
mv ruboi-one-or-two-beads-ela-ruboi-satk-k-b-jiw-t-buj-3-/data/versionXML.flextext ruboi-one-or-two-beads-ela-ruboi-satk-k-b-jiw-t-buj-3-.xml
mv shaw-forbes-persian-stories/data/versionXML.flextext shaw-forbes-persian-stories.xml
mv shaw-wakhi-tale/data/versionXML.flextext shaw-wakhi-tale.xml
mv sycamore-msk-t-nor-2-/data/versionXML.flextext sycamore-msk-t-nor-2-.xml
mv the-ant-la-fourmi-gsk-mirprit-3-/data/versionXML.flextext the-ant-la-fourmi-gsk-mirprit-3-.xml
mv the-bear-and-fox-s-friendship-msk-n-dum-t-n-xt-ir-osnodori/data/versionXML.flextext the-bear-and-fox-s-friendship-msk-n-dum-t-n-xt-ir-osnodori.xml
mv the-devil-s-fortresses-ela-diw-qlaji-/data/versionXML.flextext the-devil-s-fortresses-ela-diw-qlaji-.xml
mv the-farmer-and-his-wife-ela-polizbon-t-jaw-k-nd/data/versionXML.flextext the-farmer-and-his-wife-ela-polizbon-t-jaw-k-nd.xml
mv the-hunter-and-the-white-snake-msk-kort-i-t-ruxn-fuks-2-/data/versionXML.flextext the-hunter-and-the-white-snake-msk-kort-i-t-ruxn-fuks-2-.xml
mv the-king-and-his-two-sons-ela-pod-o-t-jaw-bu-p-t-r/data/versionXML.flextext the-king-and-his-two-sons-ela-pod-o-t-jaw-bu-p-t-r.xml
mv the-king-and-his-wife-ela-pod-o-t-jaw-k-nd-3-/data/versionXML.flextext the-king-and-his-wife-ela-pod-o-t-jaw-k-nd-3-.xml
mv the-king-s-son-and-the-vizier-s-son-msk-pod-o-p-tr-t-w-zir-p-t-r/data/versionXML.flextext the-king-s-son-and-the-vizier-s-son-msk-pod-o-p-tr-t-w-zir-p-t-r.xml
mv the-miller-ela-x-orgdor/data/versionXML.flextext the-miller-ela-x-orgdor.xml
mv the-miller-pkh-ji-x-orgvung-tu/data/versionXML.flextext the-miller-pkh-ji-x-orgvung-tu.xml
mv the-vizier-s-daughter-msk-v-zirdixtar/data/versionXML.flextext the-vizier-s-daughter-msk-v-zirdixtar.xml
mv three-pieces-of-advice-gsk-tru-nasiat-3-/data/versionXML.flextext three-pieces-of-advice-gsk-tru-nasiat-3-.xml
mv two-friends-ela-bu-osno/data/versionXML.flextext two-friends-ela-bu-osno.xml
mv wakhan-msk-waxon-done-/data/versionXML.flextext wakhan-msk-waxon-done-.xml
mv wakhi-proverbs-ela-c-ikwor-mtali-/data/versionXML.flextext wakhi-proverbs-ela-c-ikwor-mtali-.xml
mv when-the-apricot-is-unripe-msk-t-wan-ki-p-nd-k-vit-j/data/versionXML.flextext when-the-apricot-is-unripe-msk-t-wan-ki-p-nd-k-vit-j.xml
mv wish-good-and-you-will-get-good-msk-baf-xoi-tsar-baf-win-3-/data/versionXML.flextext wish-good-and-you-will-get-good-msk-baf-xoi-tsar-baf-win-3-.xml
mv wukh-homeland-msk-wux-w-tan/data/versionXML.flextext wukh-homeland-msk-wux-w-tan.xml
mv you-are-the-vision-of-my-eyes-ela-zi-ts-zmi-nazar-t-tu/data/versionXML.flextext you-are-the-vision-of-my-eyes-ela-zi-ts-zmi-nazar-t-tu.xml
mv you-should-come-to-kuybish-sometime-msk-tu-iloj-kujbi-w-zi-done-/data/versionXML.flextext you-should-come-to-kuybish-sometime-msk-tu-iloj-kujbi-w-zi-done-.xml
